apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ceph-rbd-volumeclaim
spec:
  storageClassName: ocs-storagecluster-ceph-rbd
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi
