apiVersion: v1
kind: Secret
metadata:
  name: minio-credentials
stringData:
  data: |
    [default]
    aws_access_key_id     = accesstXT9EEbxDWpLgWST4ZjmvKEQ
    aws_secret_access_key = secret3xmvLC4PXZGohuHHmamL43SG
