# This secret must exist or Velero pods won't start.
# None of the values in this secret are actually used.
apiVersion: v1
kind: Secret
metadata:
  name: cloud-credentials
stringData:
  cloud: |
    [default]
    aws_access_key_id     = dummy
    aws_secret_access_key = dummy
