# This secret must exist or Velero pods won't start.
# None of the values in this secret are actually used by the core Velero.
# If Velero vSphere plugin is used, this secret is required. Velero vSphere
# plugin references this cloud-credentails secret.
apiVersion: v1
kind: Secret
metadata:
  name: cloud-credentials
stringData:
  data: |
    [default]
    aws_access_key_id     = insert_your_access_key_id_here
    aws_secret_access_key = insert_your_secret_access_key_here
