apiVersion: oadp.openshift.io/v1alpha1
kind: Velero
metadata:
  name: velero
spec:
  olmManaged: true
  defaultVeleroPlugins:
    - aws
    - csi
    - vsphere
  veleroFeatureFlags:
    - EnableCSI
    - EnableLocalMode
  enableRestic: true
  useUpstreamImages: true
  # If you need to install Velero without a default backup storage location
  # NoDefaultBackupLocation flag is required for confirmation
  noDefaultBackupLocation: true
